### ISSUE TITLE
【Android】-【5.4.666】：【onNetworkChange 事件闪退】

### ISSUE THREAD

**Issue by zwb474287221** [tencentyun/TIMSDK#1025]
【当前现象】：onNetworkChange 事件闪退
【集成包】：imsdk-plus:5.4.666
【机型】：![image](https://user-images.githubusercontent.com/32866552/127823395-da34a777-5578-4d7b-af6a-3983e7c2c8dc.png)
【之前版本有无此问题】：imsdk-smart:5.3.435之前没有，imsdk-plus:5.4.666有
【有无日志或者描述、截图】：
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.tencent.imsdk.common.NetworkInfoCenter@116c1c4
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.tencent.imsdk.manager.BaseManager.onNetworkChange(:16)
       at com.tencent.imsdk.common.NetworkInfoCenter.onNetworkChanged(:208)
       at com.tencent.imsdk.common.NetworkInfoCenter.onReceive(:45)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，onNetworkChange 事件闪退的问题，目前这边没有在相关文档中查到此api方法，这边需要您提供下此方法的相关代码，建议更新使用新版本sdk
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Wan7451** [comment]
这个问题解决了么？我这里是 oppo设备居多

**Comment by vinsonswang** [comment]
> 这个问题解决了么？我这里是 oppo设备居多

已经解决了，麻烦升级到最新版本
