### ISSUE TITLE
TIMManagerExt.getInstanceById(loginUser).getConversationList() 大概率崩溃

### ISSUE THREAD

**Issue by Gloud-Zhao** [tencentyun/TIMSDK#118]
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.imsdk.conversation.ConversationManager.nativeGetConversations(java.util.List) (tried Java_com_tencent_imsdk_conversation_ConversationManager_nativeGetConversations and Java_com_tencent_imsdk_conversation_ConversationManager_nativeGetConversations__Ljava_util_List_2)
        at com.tencent.imsdk.conversation.ConversationManager.nativeGetConversations(Native Method)
        at com.tencent.imsdk.conversation.ConversationManager.getConversationList(ConversationManager.java:470)
        at com.tencent.imsdk.ext.message.TIMManagerExt.getConversationList(TIMManagerExt.java:81)

**Comment by cldz123** [comment]
这个是问题原因是ImSDK的库文件还没加载，就调用了native方法。
麻烦在使用所有功能之前，调用 TIMManager.getInstance().init 初始化

**Comment by Gloud-Zhao** [comment]
> 这个是问题原因是ImSDK的库文件还没加载，就调用了native方法。
> 麻烦在使用所有功能之前，调用 TIMManager.getInstance().init 初始化

肯定调用init了，这个问题不是每次必现，坐等更新

**Comment by whalehe** [comment]
您好，可以用最新版本验证下。
