### ISSUE TITLE
聊天界面崩溃

### ISSUE THREAD

**Issue by yaoxin2017** [tencentyun/TIMSDK#18]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2b04f85 position=21 id=-1, oldPos=11, pLpos:11 scrap [attachedScrap] tmpDetached no parent} com.tencent.qcloud.uikit.business.chat.view.ChatListView{3535f52 VFED..... ......I. 0,135-1080,1666 #7f09012c app:id/chat_list}, adapter:com.tencent.qcloud.uikit.business.chat.view.widget.ChatAdapter@61ff465, layout:android.support.v7.widget.LinearLayoutManager@330053a, context:com.feidi.dida.news.conversation.ChatActivity@e406130
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)
	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4928)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
	at android.view.Choreographer.doCallbacks(Choreographer.java:841)
	at android.view.Choreographer.doFrame(Choreographer.java:769)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
	at android.os.Handler.handleCallback(Handler.java:793)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:176)
	at com.feidi.dida.execption.CrashHandler$1.run(CrashHandler.java:53)
	at android.os.Handler.handleCallback(Handler.java:793)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by vinsonswang** [comment]
请问，TUIKit是在主线程 还是 其他线程初始化的？

**Comment by learyR** [comment]
```

  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{ebd559c position=35 id=-1, oldPos=15, pLpos:15 scrap [attachedScrap] tmpDetached no parent} com.tencent.qcloud.tim.uikit.modules.chat.layout.message.MessageLayout{bb3d028 VFED..... ........ 0,135-1080,1209 #7f0900ba app:id/chat_message_layout}, adapter:com.tencent.qcloud.tim.uikit.modules.chat.layout.message.MessageListAdapter@bec0141, layout:android.support.v7.widget.LinearLayoutManager@52486e6, context:dbc.dreambigcareer.com.view.activity.tim.ChatActivity@e1cca5b
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)
        at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:407)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
@vinsonswang 请问这个问题解决没有呢，我这边也遇到这个bug，是偶现的
tuikit是在Application中初始化的，也是登录成功的。我是在使用saveMessage之后调用了loadMessages(null),然后就会偶发这个bug。

**Comment by learyR** [comment]
版本号是4.5.111

**Comment by liguangming** [comment]
这个问题解决没有呢 我也遇到了
