### ISSUE TITLE
升级新版后报异常 Unable to instantiate receiver com.tencent.qalsdk.core.NetConnInfoCenter: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qalsdk.core.NetConnInfoCenter"

### ISSUE THREAD

**Issue by Gloud-Zhao** [tencentyun/TIMSDK#206]
java.lang.RuntimeException: Unable to instantiate receiver com.tencent.qalsdk.core.NetConnInfoCenter: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qalsdk.core.NetConnInfoCenter" on path: DexPathList[[zip file "/data/app/cn.xx.client.mobile-2/base.apk"],nativeLibraryDirectories=[/data/app/cn.xx.client.mobile-2/lib/arm, /data/app/cn.xx.client.mobile-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3343)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qalsdk.core.NetConnInfoCenter" on path: DexPathList[[zip file "/data/app/cn.xx.client.mobile-2/base.apk"],nativeLibraryDirectories=[/data/app/cn.xx.client.mobile-2/lib/arm, /data/app/cn.xx.client.mobile-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3338)
	... 8 more
java.lang.ClassNotFoundException: Didn't find class "com.tencent.qalsdk.core.NetConnInfoCenter" on path: DexPathList[[zip file "/data/app/cn.xx.client.mobile-2/base.apk"],nativeLibraryDirectories=[/data/app/cn.xx.client.mobile-2/lib/arm, /data/app/cn.xx.client.mobile-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3338)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by whalehe** [comment]
您好，最新版本已经废弃这个类。可以在AndroidManifest.xml中去掉注册声明，详情可以参考最新Demo
