### ISSUE TITLE
【Android兼容】-【4.4.627】：【聊天窗口显示图片消息crash】

### ISSUE THREAD

**Issue by ZhengShang** [tencentyun/TIMSDK#234]
- 【Android】-【4.4.627】：【聊天窗口显示图片消息crash】
- 【集成包】：TUIKIT
- 【当前现象】：在聊天窗口发送图片后, app直接崩溃, log显示找不到centerCrop()方法. 查询后得知, 此问题由于tuikit库和我本地的glide本地版本不一致造成. 希望tuikit后续版本可以增加一个设置ImageEngine的接口出来.
- 【机型】：锤子坚果Pro2s
- 【之前版本有无此问题】：未知
- 【截图】：
![image](https://user-images.githubusercontent.com/9746290/61285798-28cea180-a7f4-11e9-9a68-d0e3e4846c04.png)
- 【日志】：
 java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/yougao.com.yougao-tCDZ-qzFPBAims9gu7q2_w==/split_lib_dependencies_apk.apk)
        at com.tencent.qcloud.tim.uikit.component.picture.imageEngine.impl.GlideEngine.loadCornerImage(GlideEngine.java:84)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.performImage(MessageImageHolder.java:139)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.layoutVariableViews(MessageImageHolder.java:77)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageContentHolder.layoutViews(MessageContentHolder.java:187)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.MessageListAdapter.onBindViewHolder(MessageListAdapter.java:80)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6937)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6979)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5896)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6163)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6002)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5998)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4033)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3445)
        at android.view.View.measure(View.java:22519)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:687)
        at android.view.View.measure(View.java:22519)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
2019-07-16 16:54:17.819 8698-8698/yougao.com.yougao E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6757)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:993)
        at android.view.View.measure(View.java:22519)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2818)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1872)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2140)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1737)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7794)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
        at android.view.Choreographer.doCallbacks(Choreographer.java:781)
        at android.view.Choreographer.doFrame(Choreographer.java:716)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:961)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6901)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by whalehe** [comment]
您好，这是使用同一个库冲突问题导致的。你目前可以在代码中先使用一个版本的glide，我们目前使用的是com.github.bumptech.glide:glide:4.7.1，后续我们争取去掉这些第三方库

**Comment by charmeleon2** [comment]
我也遇到这问题了，4.7.1实在是降不下来，glideapp编译通不过，试了下4.8可以用，希望腾讯工程师早日把图片加载的接口独立出来（从4.9开始又不需要glideapp了，回到了早前3.x那种使用模式）

**Comment by fairytale110** [comment]
![image](https://user-images.githubusercontent.com/30248926/63566053-26ebc100-c59e-11e9-891c-48703bbe3efe.png)


自己写，方便维护
