### ISSUE TITLE
【Android】-【4.4.716】：【MessageImageHolder 报 divide by zero】

### ISSUE THREAD

**Issue by HystrixWong** [tencentyun/TIMSDK#242]
【Android】-【4.4.716】：【MessageImageHolder 报 divide by zero】
【当前现象】：进入聊天界面获取消息崩溃，当前的会话消息里面有文字、图片、视频
【集成包】：TUIKIT
【机型】：荣耀9
【之前版本有无此问题】：未知
【有无日志或者描述】：
` java.lang.ArithmeticException: divide by zero
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.getImageParams(MessageImageHolder.java:120)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.performImage(MessageImageHolder.java:131)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.layoutVariableViews(MessageImageHolder.java:77)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageContentHolder.layoutViews(MessageContentHolder.java:207)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.MessageListAdapter.onBindViewHolder(MessageListAdapter.java:80)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

**Comment by whalehe** [comment]
您好，感谢您的反馈，这个问题，下个版本会修复~

**Comment by whalehe** [comment]
4.4.900 已修复
