### ISSUE TITLE
Android github开源demo登录运行crash

### ISSUE THREAD

**Issue by beibeiandroid** [tencentyun/TIMSDK#281]
08-18 01:04:58.501 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: Java Crash Happen cause by main(1)
08-18 01:04:58.548 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: stack frame :15, has cause false
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: #++++++++++Record By Bugly++++++++++#
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # PKG NAME: com.tencent.qcloud.tim.tuikit
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # APP VER: 4.4.900
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # LAUNCH TIME: 2019-08-18 01:04:37
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # CRASH TYPE: JAVA_CRASH
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # CRASH TIME: 2019-08-18 01:04:58
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # CRASH PROCESS: com.tencent.qcloud.tim.tuikit
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # CRASH THREAD: main
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # REPORT ID: 7e28393d-4086-4e7d-8409-a1914da34bc2
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # CRASH DEVICE: SM-G955F ROOTED
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # RUNTIME AVAIL RAM:1017118720 ROM:65112870912 SD:65112870912
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # RUNTIME TOTAL RAM:1055047680 ROM:65921708032 SD:65921708032
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: # CRASH STACK: 
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: java.lang.IllegalArgumentException: key.length == 0
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:62)
        at com.tencent.qcloud.tim.demo.signature.GenerateTestUserSig.hmacsha256(GenerateTestUserSig.java:149)
        at com.tencent.qcloud.tim.demo.signature.GenerateTestUserSig.GenTLSSignature(GenerateTestUserSig.java:119)
        at com.tencent.qcloud.tim.demo.signature.GenerateTestUserSig.genTestUserSig(GenerateTestUserSig.java:84)
        at com.tencent.qcloud.tim.demo.login.LoginForDevActivity$1.onClick(LoginForDevActivity.java:60)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
08-18 01:04:58.553 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
08-18 01:04:58.739 3490-3699/com.tencent.qcloud.tim.tuikit E/CrashReport: [Upload] Failed to upload(1) crash: status of server is 4
08-18 01:04:58.793 3490-3490/com.tencent.qcloud.tim.tuikit E/CrashReport: sys default last handle start!
    
    --------- beginning of crash
08-18 01:04:58.797 3490-3490/com.tencent.qcloud.tim.tuikit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.qcloud.tim.tuikit, PID: 3490
    java.lang.IllegalArgumentException: key.length == 0
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:62)
        at com.tencent.qcloud.tim.demo.signature.GenerateTestUserSig.hmacsha256(GenerateTestUserSig.java:149)
        at com.tencent.qcloud.tim.demo.signature.GenerateTestUserSig.GenTLSSignature(GenerateTestUserSig.java:119)
        at com.tencent.qcloud.tim.demo.signature.GenerateTestUserSig.genTestUserSig(GenerateTestUserSig.java:84)
        at com.tencent.qcloud.tim.demo.login.LoginForDevActivity$1.onClick(LoginForDevActivity.java:60)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    
    
    --------- beginning of system
08-18 01:04:58.842 1424-1424/? E/EGL_emulation: tid 1424: eglCreateSyncKHR(1479): error 0x3004 (EGL_BAD_ATTRIBUTE)

【集成包】：TUIKIT
【当前现象】点击登录crash 
【机型】：任何
【之前版本有无此问题】：之前没有这个问题

真是醉了 上传不验证的吗 腾讯垃圾

**Comment by beibeiandroid** [comment]
111

**Comment by vinsonswang** [comment]
GenerateTestUserSig 中的 SECRETKEY 需要填上您在腾讯云即时通信 IM 控制台获取的秘钥信息，参考文档：https://cloud.tencent.com/document/product/269/36838
同时源码里我们也会对 SECRETKEY 做下判空处理
