### ISSUE TITLE
【Android】-【4.5.55】：【集成Tuikit，发送图片crash】

### ISSUE THREAD

**Issue by wschkd123** [tencentyun/TIMSDK#406]
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，发送图片时crash。
【机型】：如小米8
【之前版本有无此问题】：从第一次集成4.5.15就有这个问题
【问题原因】：tuikit里面依赖的glide版本兼容的问题。tuikit依赖glide版本为4.7.1，建议改为4.9.0
【有无日志或者截图】：
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: shop.sellfast.android, PID: 18310
    java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/shop.sellfast.android--2NMkVUdcGc4_gePsRD20A==/base.apk)
        at com.tencent.qcloud.tim.uikit.component.picture.imageEngine.impl.GlideEngine.loadCornerImage(GlideEngine.java:86)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.performImage(MessageImageHolder.java:142)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageImageHolder.layoutVariableViews(MessageImageHolder.java:77)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.holder.MessageContentHolder.layoutViews(MessageContentHolder.java:231)
        at com.tencent.qcloud.tim.uikit.modules.chat.layout.message.MessageListAdapter.onBindViewHolder(MessageListAdapter.java:81)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:682

**Comment by parkhuang** [comment]
感谢反馈，我们评估一下
