### ISSUE TITLE
【Android】-【4.5.45】：【部分用户通讯录列表排序crash】

### ISSUE THREAD

**Issue by Honjay** [tencentyun/TIMSDK#462]
【集成包】：TUIKIT
【当前现象】：部分用户通讯录排序时crash，所有机型，必现5
【机型】：所有机型
【日志】：
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeLo(TimSort.java:777)
at java.util.TimSort.mergeAt(TimSort.java:514)
at java.util.TimSort.mergeCollapse(TimSort.java:441)
at java.util.TimSort.sort(TimSort.java:245)
at java.util.Arrays.sort(Arrays.java:1498)
at java.util.ArrayList.sort(ArrayList.java:1470)
at java.util.Collections.sort(Collections.java:201)
**atcom.tencent.qcloud.tim.uikit.component.indexlib.IndexBar.helper.IndexBarDataHelperImpl.sortSourceDatas(IndexBarDataHelperImpl.java:88)**
atcom.tencent.qcloud.tim.uikit.component.indexlib.IndexBar.widget.IndexBar.initSourceDatas(IndexBar.java:358) 
atcom.tencent.qcloud.tim.uikit.component.indexlib.IndexBar.widget.IndexBar.setSourceDatas(IndexBar.java:341) atcom.tencent.qcloud.tim.uikit.modules.contact.ContactListView.setDataSource(ContactListView.java:107)                                                                                 atcom.tencent.qcloud.tim.uikit.modules.contact.ContactListView$1.onSuccess(ContactListView.java:217)                                                                           atcom.tencent.qcloud.tim.uikit.modules.contact.ContactListView$1.onSuccess(ContactListView.java:186)
at com.tencent.imsdk.common.ICallback$1.run(ICallback.java:26)
at android.os.Handler.handleCallback(Handler.java:873)                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6680)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
![image](https://user-images.githubusercontent.com/19324984/67820375-f40cfe80-faf3-11e9-8eec-88d3da0b9ccd.png)
![image](https://user-images.githubusercontent.com/19324984/67820404-0424de00-faf4-11e9-9c0f-67d246ab778e.png)

**Comment by parkhuang** [comment]
好的，感谢反馈，我们分析一下

**Comment by parkhuang** [comment]
会在即将发布的4.6.1中fix
