### ISSUE TITLE
【小程序】-【2.1.3】：【发送语音，显示无法发送空文件】。【发送图片无响应】

### ISSUE THREAD

**Issue by newStudent-ls** [tencentyun/TIMSDK#492]
![Uploading image.png…]()

**Comment by newStudent-ls** [comment]
`recorderManager.onStop((res) => {
            console.log('recorder stop')
            wx.hideLoading()
            if (this.data.canSend) {
                if (res.duration < 1000) {
                    $u.showToast("录音时间太短");
                } else {
                    console.log(res);
                    console.log(IM.getMessageChar());
                    console.log(IM.getMessageChar().sendMessage.voice(res));
                    IM.getMessageChar().sendMessage.voice(res).send(message=>{
                        this.addMessage(message);
                        console.log("发送录音成功");
                    },error=>{
                        console.log(error);
                    })
                }
            }
        })`

**Comment by newStudent-ls** [comment]
tim-wx-sdk 2.1.3

**Comment by newStudent-ls** [comment]
`message: e
ID: "GROUP102250-1507350001-4319880-1"
clientSequence: 1507350001
conversationID: "GROUP102250"
conversationSubType: undefined
conversationType: "GROUP"
flow: "out"
from: "e7a0cbfd8b4442039fd7fe874b056749"
geo: {}
isPlaceMessage: 0
isRead: 1
isResend: 0
isSystemMessage: 0
messagePriority: 0
payload:
downloadFlag: 2
remoteAudioUrl: ""
second: 2
size: 118598
url: "wxfile://tmp_9617d66f524ca4d28edea882d92f281a.m4a"
uuid: "1400200009-e7a0cbfd8b4442039fd7fe874b056749-YMiDCD3RnVmaJIS5OaZK5Zq7PM6IqLMR"
__proto__: Object
protocol: "JSON"
random: 4319880
sequence: 0
status: "fail"
time: 1573110456
to: "102250"
type: "TIMSoundElem"
_elements: [e]
_error: 0
_errorInfo: ""
elements: (...)`

**Comment by newStudent-ls** [comment]
`sendMessage error: t: 无法发送空文件
    at o.value (weapp:///miniprogram_npm/tim-wx-sdk/index.js:2659:63)
    at e._onOperatedHandle (weapp:///miniprogram_npm/tim-wx-sdk/index.js:4208:37)
    at e.value (weapp:///miniprogram_npm/tim-wx-sdk/index.js:2164:100)
    at weapp:///miniprogram_npm/tim-wx-sdk/index.js:2894:115
    at t ([publib]:1:80645)
    at [publib]:1:80767
    at e ([publib]:1:83223)
    at e.exports ([publib]:1:42170)
    at y.(anonymous function) ([publib]:1:47573)
    at Number.r ([publib]:1:47272)`

**Comment by newStudent-ls** [comment]
错误码2108 无法发送空文件

**Comment by newStudent-ls** [comment]
还有一个现象 图片发送 没结果 也不报错，直接就消失了

**Comment by newStudent-ls** [comment]
图片发送没有回调 promise.then(imResponse=> { })不会执行 catch也没有

**Comment by newStudent-ls** [comment]
图片发送调用createImageMessage 生成的状态status 是fail.我看demo里面生成的是unSend.

**Comment by newStudent-ls** [comment]
图片的imageFormat 是255.   demo里面是GIF

**Comment by newStudent-ls** [comment]
cos插件引错，小程序用wx，不是js复制错了 蛋疼
