### ISSUE TITLE
只是升级了一下SDK到4.6.101  其他的没动 启动app时出现了崩溃 日志如下

### ISSUE THREAD

**Issue by wangcaiwen5** [tencentyun/TIMSDK#638]
java.lang.NoSuchMethodError: no static method "Lcom/tencent/imsdk/manager/NativeManager;.getNetSSID()Ljava/lang/String;"
        at com.tencent.imsdk.manager.NativeManager.nativeInitSdk(Native Method)
        at com.tencent.imsdk.manager.BaseManager.init(BaseManager.java:140)
        at com.tencent.imsdk.TIMManager.init(TIMManager.java:73)
        at com.tencent.qcloud.tim.uikit.TUIKitImpl.initIM(TUIKitImpl.java:90)
        at com.tencent.qcloud.tim.uikit.TUIKitImpl.init(TUIKitImpl.java:60)
        at com.tencent.qcloud.tim.uikit.TUIKit.init(TUIKit.java:19)

**Comment by parkhuang** [comment]
之前有客户反馈这个问题，都是因为so和java代码不匹配导致的，请检查一下版本
