### ISSUE TITLE
【Android】【4.6.102】【Crash 崩溃】

### ISSUE THREAD

**Issue by 13120241790** [tencentyun/TIMSDK#654]
【Android】【4.6.102】【Crash 崩溃】

集成包 : TUIKit
问题描述 ：自定义会话部分 
2020-03-24 09:32:11.453 29752-29752/? E/CrashReport: java.lang.ClassCastException: android.widget.ImageView cannot be cast to com.tencent.qcloud.tim.uikit.modules.conversation.base.ConversationIconView
        at com.tencent.qcloud.tim.uikit.modules.conversation.holder.ConversationCustomHolder.<init>(ConversationCustomHolder.java:31)
        at com.tencent.qcloud.tim.uikit.modules.conversation.ConversationListAdapter.onCreateViewHolder(ConversationListAdapter.java:63)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at com.tencent.qcloud.tim.uikit.component.CustomLinearLayoutManager.onLayoutChildren(CustomLinearLayoutManager.java:30)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)

个人本地已处理 还请在 SDK 处理下以免后续开发者使用遇到同样问题

**Comment by vinsonswang** [comment]
感谢反馈！
