### ISSUE TITLE
   com.tencent.qcloud.tim.uikit.modules.conversation.ConversationLayout无法引用此view

### ISSUE THREAD

**Issue by tcwy123456** [tencentyun/TIMSDK#664]
android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.tencent.qcloud.tim.uikit.modules.conversation.ConversationLayout
    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class com.tencent.qcloud.tim.uikit.modules.conversation.ConversationLayout
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.vedio_recruitment.main.msg.Fragment.FriendFgm.onCreateView(FriendFgm.java:46)
        at android.app.Fragment.performCreateView(Fragment.java:2522)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.tencent.qcloud.tim.uikit.component.TitleBarLayout
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class com.tencent.qcloud.tim.uikit.component.TitleBarLayout
     Caused by: java.lang.reflect.InvocationTargetException

**Comment by KingTomm** [comment]
同有这个问题，请问您解决了吗
