### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference

### ISSUE THREAD

**Issue by HMY314** [tencentyun/TIMSDK#69]
Android SDK4.2.2
java.lang.RuntimeException: Unable to create service com.tencent.imsdk.session.remote.SessionService: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3075)
	at android.app.ActivityThread.access$2100(ActivityThread.java:170)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.os.Parcel.readException(Parcel.java:1583)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:122)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
	at com.tencent.imsdk.session.remote.SessionService.addJob(SessionService.java:235)
	at com.tencent.imsdk.session.remote.SessionService.addRebootTimer(SessionService.java:213)
	at com.tencent.imsdk.session.remote.SessionService.onCreate(SessionService.java:114)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3065)
	... 8 more

**Comment by tangtingyun** [comment]
请教一下 怎么修复的？
