### ISSUE TITLE
【Android】-【4.7.10】： NullPointerException

### ISSUE THREAD

**Issue by qyxxjd** [tencentyun/TIMSDK#747]
【Android】-【4.7.10】：【SDK空指针导致App闪退】
【集成包】：TUIKIT
【当前现象】：后台收集到的空指针闪退
【机型】：OPPO

```
Device info：
SDK: 29
OS Version: 10
Vendor: OPPO
Model: PCRM00
CPU ABI: arm64-v8a armeabi-v7a armeabi 
------------------------------------

2020-06-04 14:42:00

java.lang.ExceptionInInitializerError
	at com.tencent.qcloud.tim.uikit.component.face.FaceManager.getEmojiList(FaceManager.java:39)
	at com.tencent.qcloud.tim.uikit.component.face.FaceFragment.onCreate(FaceFragment.java:69)
	at android.app.Fragment.performCreate(Fragment.java:2515)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2999)
	at android.app.FragmentController.dispatchCreate(FragmentController.java:173)
	at android.app.Activity.onCreate(Activity.java:1539)
	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:149)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:313)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at com.miaoxi.ui.base.AppBaseActivity.onCreate(AppBaseActivity.kt:81)
	at android.app.Activity.performCreate(Activity.java:7989)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3506)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3674)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2237)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at com.tencent.qcloud.tim.uikit.utils.ScreenUtil.getPxByDp(ScreenUtil.java:88)
	at com.tencent.qcloud.tim.uikit.component.face.FaceManager.<clinit>(FaceManager.java:31)
	... 30 more
```

**Comment by vinsonswang** [comment]
感谢反馈！
问题原因是调用 ScreenUtil.getPxByDp 时需要用到 TUIKit.init 接口中传入的 Context 参数，而没有调用初始化接口此参数为空导致的。我们会规避此问题，同时建议您先调用初始化后再调用其他接口，另外如果您使用源码集成的话也可以自己修改接口 getPxByDp，调用时传入 Context 参数。
