### ISSUE TITLE
http request failed.Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl

### ISSUE THREAD

**Issue by TSsimeon** [tencentyun/TIMSDK#785]
issue标题：android 10.0 调用v2TIMImage.downloadImage下载图片失败
【平台】-【版本号】：Android10 SDK:4.8.50
issue内容：

【当前现象】：android 10.0 调用v2TIMImage.downloadImage下载图片失败,其他版本手机下载正常
【集成包】：IMSDK
【机型】：mix2s
【之前版本有无此问题】：不知
【有无日志或者描述、截图】：
2020-07-08 16:20:25.231 20587-20720/com.tsimeon.android E/imsdk: TIM: 170   2020-07-08 16:20:25.231/E/20587-20720     /IMSDK       -HttpClient.0                                               /http request failed.Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
2020-07-08 16:20:25.231 20587-20632/com.tsimeon.android E/imsdk: TIM: 171   2020-07-08 16:20:25.231/E/20587-20632     /Common      -imcore_comm.cpp.53  operator()                             /download elem failed|url:https://cos.ap-shanghai.myqcloud.com/6244-shanghai-007-shared-01-1256635546/8804-1400377178/8254-joker/764bf19cf43f4b063b1dab00a8febc37.jpg|path:/storage/emulated/0/Android/data/com.tsimeon.android/cache/cache/im/image/myUserID0_1400377178_joker_764bf19cf43f4b063b1dab00a8febc37.jpg|code:-1|desc:java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
        at com.didichuxing.doraemonkit.aop.urlconnection.ObsoleteUrlFactory$OkHttpsURLConnection.setSSLSocketFactory(ObsoleteUrlFactory.java:1300)
        at com.tencent.imsdk.looper.HttpClient$3.run(HttpClient.java:135)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    	at java.util.concurrent.ThreadPoolExecutor$W

**Comment by vinsonswang** [comment]
这个貌似是 OkHttp 库的问题，建议换个http库或者用原生的验证一下

**Comment by TSsimeon** [comment]
用okhttp4.x系列就有问题现在换到了3.x就可以了。
