### ISSUE TITLE
【Android】-【IMSdk 4.4.479】：【更新imsdk到4.9.1 TXLiveBase.getSDKVersionStr() crash】

### ISSUE THREAD

**Issue by yabee5566** [tencentyun/TIMSDK#817]
issue标题：
更新imsdk到4.9.1 TXLiveBase.getSDKVersionStr() 觸發 crash, 但其後消息收發都正常, 到底更新後使用TXLiveBase.getSDKVersionStr()檢測集成成功這事情還在4.9.1還valid嗎？

【当前现象】：

【集成包】：IMSDK
【机型】：Android所有機台
【之前版本有无此问题】：如4.4.479没有，更新上4.9.1有
【有无日志或者描述、截图】：

2020-08-18 13:34:57.659 10159-10159/com.baulong.phonelive E/CrashReport: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion() (tried Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion and Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion__)
        at com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion(Native Method)
        at com.tencent.liteav.basic.util.TXCCommonUtil.getSDKVersionStr(TXCCommonUtil.java:55)
        at com.tencent.rtmp.TXLiveBase.getSDKVersionStr(TXLiveBase.java:177)
        at com.baulong.main.views.MainMeViewHolder.onResume(MainMeViewHolder.java:146)
        at com.baulong.common.activity.AbsActivity.onResume(AbsActivity.java:263)
        at com.baulong.main.activity.MainActivity.onResume(MainActivity.java:326)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8125)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4331)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4373)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)

[module的 build.gradle.zip](https://github.com/tencentyun/TIMSDK/files/5088419/module.build.gradle.zip)

**Comment by itdais** [comment]
我也出现相同的错误

**Comment by itdais** [comment]
解决了  解决方法是拷贝 imsdk 的 aar 里面的 jni/armeabi-v7a/libImSDK.so 到源码工程的 src/main/jniLibs/armeabi 目录里，并在 build.gradle 中加载即可。
https://cloud.tencent.com/document/product/269/32483#.E5.9C.A8-armeabi-.E5.B9.B3.E5.8F.B0.E4.B8.8A-sdk-.E6.8A.A5.26quot.3Bjava.lang.unsatisfiedlinkerror.3A-no-implementation-found-for.26quot.3B.E9.94.99.E8.AF.AF.E8.AF.A5.E5.A6.82.E4.BD.95.E5.A4.84.E7.90.86.EF.BC.9F

**Comment by yabee5566** [comment]
我開工單他叫我用v2不要用v1的api
然後我發現imsdk TXLiveBase 似乎是兩回事 要另外更新trtc的sdk

**Comment by JunkmenDream** [comment]
> issue标题：
> 更新imsdk到4.9.1 TXLiveBase.getSDKVersionStr() 觸發 crash, 但其後消息收發都正常, 到底更新後使用TXLiveBase.getSDKVersionStr()檢測集成成功這事情還在4.9.1還valid嗎？
> 
> 【当前现象】：
> 
> 【集成包】：IMSDK
> 【机型】：Android所有機台
> 【之前版本有无此问题】：如4.4.479没有，更新上4.9.1有
> 【有无日志或者描述、截图】：
> 
> 2020-08-18 13:34:57.659 10159-10159/com.baulong.phonelive E/CrashReport: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion() (tried Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion and Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion__)
> at com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion(Native Method)
> at com.tencent.liteav.basic.util.TXCCommonUtil.getSDKVersionStr(TXCCommonUtil.java:55)
> at com.tencent.rtmp.TXLiveBase.getSDKVersionStr(TXLiveBase.java:177)
> at com.baulong.main.views.MainMeViewHolder.onResume(MainMeViewHolder.java:146)
> at com.baulong.common.activity.AbsActivity.onResume(AbsActivity.java:263)
> at com.baulong.main.activity.MainActivity.onResume(MainActivity.java:326)
> at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
> at android.app.Activity.performResume(Activity.java:8125)
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4331)
> at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4373)
> at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:216)
> at android.app.ActivityThread.main(ActivityThread.java:7464)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
> 
> [module的 build.gradle.zip](https://github.com/tencentyun/TIMSDK/files/5088419/module.build.gradle.zip)

-----------------------------------------------------------------------------------------------------------------------------
这个是因为AS中TRTC SDK缓存问题。需要清理下AS缓存
