### ISSUE TITLE
Android 11 java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String 

### ISSUE THREAD

**Issue by cuihp** [tencentyun/TIMSDK#894]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：
【Android】-【5.0.6~5.0.10】：【b】
issue内容：
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion() (tried Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion and Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion__)
        at com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion(Native Method)
        at com.tencent.liteav.basic.util.TXCCommonUtil.getSDKVersion(TXCCommonUtil.java:39)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.init(TRTCCloudImpl.java:443)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:336)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:318)
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:41)
        at com.tencent.liteav.model.TRTCAVCallImpl.<init>(TRTCAVCallImpl.java:397)
        at com.tencent.liteav.model.TRTCAVCallImpl.sharedInstance(TRTCAVCallImpl.java:376)
        at com.tencent.liteav.AVCallManager.initVideoCallData(AVCallManager.java:155)
        at com.tencent.liteav.AVCallManager.init(AVCallManager.java:144)
        at com.tencent.qcloud.tim.uikit.TUIKitImpl$1.onSuccess(TUIKitImpl.java:119)
        at com.tencent.imsdk.v2.V2TIMManagerImpl$1.onSuccess(V2TIMManagerImpl.java:159)
        at com.tencent.imsdk.common.ICallback$1.run(ICallback.java:24)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:245)
        at android.app.ActivityThread.main(ActivityThread.java:7953)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
【当前现象】：

【集成包】：IMSDK
【机型】：一加8
【之前版本有无此问题】：如4.8.10之前没有，4.8.10有
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
-------------------------完整的示例如下：-------------------------

【Android】-【4.4.479】：【集成时报找不到GroupChatPanel类错误】
【集成包】：TUIKIT
【当前现象】：Android Studio集成新版本TUIKit，报错，无法编译通过（描述你的问题现象，错误码、错误信息 以及具体请求或者接口）
【机型】：如华为Mate 20
【之前版本有无此问题】：TUIKIT 4.4.479版本之前没有，4.4.479有
【有无日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

**Comment by Lizhz** [comment]
你好 我也遇到了同样的问题，请问你解决了吗？

**Comment by JunkmenDream** [comment]
这个原因是因为AS对于SDK不同版本的缓存冲突，清除下AS缓存即可。该问题只会出现在编译阶段，线上不会导致该问题
