### ISSUE TITLE
5.1.10 java.lang.ClassCastException: android.widget.ImageView cannot be cast to com.tencent.qcloud.tim.uikit.modules.conversation.base.ConversationIconView

### ISSUE THREAD

**Issue by xuetenglong** [tencentyun/TIMSDK#928]
java.lang.ClassCastException: android.widget.ImageView cannot be cast to com.tencent.qcloud.tim.uikit.modules.conversation.base.ConversationIconView

**Comment by xuetenglong** [comment]
java.lang.ClassCastException: android.widget.ImageView cannot be cast to com.tencent.qcloud.tim.uikit.modules.conversation.base.ConversationIconView
        at com.tencent.qcloud.tim.uikit.modules.conversation.holder.ConversationCustomHolder.<init>(ConversationCustomHolder.java:31)
        at com.tencent.qcloud.tim.uikit.modules.conversation.ConversationListAdapter.onCreateViewHolder(ConversationListAdapter.java:65)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at com.tencent.qcloud.tim.uikit.component.CustomLinearLayoutManager.onLayoutChildren(CustomLinearLayoutManager.java:33)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1858)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:407)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:728)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-12-20 15:19:25.538 7278-7278/com.tencent.qcloud.tim.tuikit I/Process: Sending signal. PID: 7278 SIG: 9

**Comment by Tencent-Alice** [comment]
您好，TIM 是使用的含UI库的吗，具体需要排查了
技术问题，欢迎私信 Q2562367495 备明来意
