### ISSUE TITLE
Bugly报空指针

### ISSUE THREAD

**Issue by MikeVoy** [tencentyun/TIMSDK#983]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：java.lang.NullPointerException:

【平台】-【版本号】：Android 9.0
issue内容：

【当前现象】：集成IM  以及专业版云点播com.tencent.liteav:LiteAVSDK_Professional:latest.release 以后  之前使用的bugly全量更新 报空指针
【集成包】：IMSDK   om.tencent.liteav:LiteAVSDK_Professional   bugly:crashreport_upgrade:1.5.0  nativecrashreport:3.8.0
【机型】：华为Nova4
【之前版本有无此问题】：未集成Im 以及云点播sdk时没有问题
【有无日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好
-------------------------完整的示例如下：-------------------------
2021-04-06 20:50:20.531 30931-30931/com.example.xnPb E/CrashReport: java.lang.NullPointerException: Attempt to read from field 'com.tencent.bugly.proguard.sa com.tencent.bugly.beta.upgrade.BetaUploadStrategy.a' on a null object reference
        at com.tencent.bugly.beta.upgrade.c.a(BUGLY:199)
        at com.tencent.bugly.beta.Beta.a(BUGLY:7)
        at com.tencent.bugly.beta.Beta.checkUpgrade(BUGLY:2)
        at com.example.xnPb.activity.home.HomeActivity.flush(HomeActivity.java:319)
        at com.example.xnPb.utils.HttpUtil$3$2.run(HttpUtil.java:244)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

![image](https://user-images.githubusercontent.com/40830151/113714085-9c2beb80-971a-11eb-87e8-00c979f0cce0.png)

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 跟您 确定下当前im sdk版本号是多少？ 具体有做什么操作？ 提供下问题复现的具体实现步骤，也可以收集下日志看下  方便进一步定位
技术问题 欢迎交流 Q2562367495  注明来意

**Comment by MikeVoy** [comment]
引入本地的·tuikit库 使用   api 'com.tencent.imsdk:imsdk:5.1.50'  在主APP的buildGradle 使用的是bugly:crashreport_upgrade:1.5.0 && bugly:nativecrashreport:3.8.0

**Comment by MikeVoy** [comment]
![image](https://user-images.githubusercontent.com/40830151/113800886-5444ad00-978a-11eb-8760-917ebadcd3a8.png)
腾讯云那边反应说是bugly内部问题 这是报错的地方
![100017429703_1617714567363_8816](https://user-images.githubusercontent.com/40830151/113800967-78a08980-978a-11eb-8f7c-5789a02accba.png)
